name: GitHub Actions Attempt

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Setup Node.js
         uses: action/setup-node@v4
         with:
            node-vertion: '18.x'
            cash: 'npm'
       - run: npm ci
       - run: npm test
       - name: Set up Python
         uses: actions/setup-python@v6
         with:
           python-version: '3.12'
        # make depends on uv
       - name: Install dependencies
         run: |
          make install
       - name: Build project
         run: |
          make build
       - name: Run linter and pytest
         run: |
          make test
          make lint
